the first step is to import the numpy package <br>
we then change the package name from numpy to np

In [1]:
import numpy as np

now, we create a numpy array from a list

In [2]:
A_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(A_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
A = np.array(A_list, dtype='int32')
print(A)

[0 1 2 3 4 5 6 7 8 9]


We can directly use a list as the first argument to the function np.array 

In [8]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

a numpy array is an object, so it has a type and an id

In [10]:
type(A)

numpy.ndarray

In [11]:
id(A)

4529518832

obtain the length of the array using the function len

In [12]:
len(A)

10

obtain the length of the array using ArrayName.shape which is a data attribute of the array

In [13]:
A.shape

(10,)

In [11]:
type(A.shape)  # it is a tuple with one element

tuple

In [14]:
LenA = A.shape[0] # get the first/only element in the tuple
print(LenA)

10


A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get an element of an array using ArrayName[index] <br>
index >=0, index < len(ArrayName)

In [15]:
A[0] # the first element

0

In [13]:
A[1] # the second element

1

In [16]:
A[LenA-1] # the last element

9

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end], <br>
where start >= 0, end >= 0, end > start 

In [17]:
A[0:3] # start from A[0], then A[1], A[2], up to but not inluding A[3]

array([0, 1, 2], dtype=int32)

In [16]:
A[1:LenA] # get elements from A[1] to A[LenA-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
A[1:] # omit end, we get elements from A[1] to A[LenA-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
A[0:0] # start == end

array([], dtype=int32)

In [19]:
A[3:0] # start < end

array([], dtype=int32)

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end: step], <br>
where start >= 0, end >= 0, end > start and step > 0 

In [22]:
A[0:3:0] # error, step is 0

ValueError: slice step cannot be zero

In [23]:
A[0:3:1] # step is 1, this is the same as A[0:3]

array([0, 1, 2])

In [24]:
A[0:3:2] # step is 2, A[0], A[2], A[4](not included, 4 > 3 in 0:3:2)

array([0, 2])

In [25]:
A[0:3:10] # step is 10, A[0], A[10](not exist)

array([0])

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end: step], <br>
where start >= 0, end >= 0, start > end and step < 0 

In [26]:
A[3:0:-1] # start is 3, end is 0, step is -1

array([3, 2, 1])

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
Now, we will use negative indexes ... <br>

In [18]:
A[-1] # the last element, A[LenA-1] => A[(LenA-1)-LenA]

9

In [28]:
A[-9] # A[1] => A[1-LenA]

1

In [19]:
A[-LenA] # A[0] => A[0-LenA]

0

get a sub-array using the notation ArrayName[start: end], <br>
where start < 0, end < 0, end > start 

In [6]:
A[-9:-1] # get elements: A[-9],A[-8],A[-7],A[-6],
         #               A[-5],A[-4],A[-3],A[-2]
         # up to but not including A[-1]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [7]:
A[-9:] # omit end, now the last element is included in the sub-array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [32]:
A[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

get a sub-array using the notation ArrayName[start: end: step], <br>
where start < 0, end < 0, end > start and step > 0 

In [20]:
A[-9:-1:3] # start is -9, end is -1, step is 3
           # A[-9], A[-6], A[-3], A[0](not included) 

array([1, 4, 7], dtype=int32)

get a sub-array using the notation ArrayName[start: end: step], <br>
where start < 0, end < 0, end < start and step < 0 

In [21]:
A[-1:-9:-3]# start is -1, end is -9, step is -3
           # A[-1], A[-4], A[-7], A[-10](not exist)

array([9, 6, 3], dtype=int32)

create an array with a predifined length <br>
initialize it with zeros or ones

In [22]:
A0 = np.zeros(10, dtype='float32')
print(A0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
A1 = np.ones(10, dtype='float32')
print(A1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


create an array with a predifined length <br>
we do not care about the initial values of the elements

In [24]:
A2 = np.empty(10)
print(A2)

[1.5e-322 0.0e+000 0.0e+000 0.0e+000 0.0e+000 0.0e+000 0.0e+000 0.0e+000
 0.0e+000 0.0e+000]


create an array with a predifined length <br>
initialize it with random numbers that follow a probability distribution<br>
use the functions in the module 'random' to generate random numbers <br>
rand: uniform distribution in 0~1 <br>
randn: normal distribution mean=0, std=1 <br>
(many functions in the module)

In [25]:
A_rand = np.random.rand(10)
print(A_rand)

[0.8713185  0.25448484 0.53343173 0.06741099 0.07074759 0.76968668
 0.86880244 0.24085773 0.0677786  0.84851331]


In [26]:
A_randn = np.random.randn(1000)
print(A_randn)

[ 3.86917375e-01 -3.66736195e-01 -2.96887041e-01  9.53708803e-02
  2.81528774e-01  3.20636963e-01 -1.28252614e+00 -9.10769404e-01
 -1.18328410e+00  6.87716547e-01  1.24116236e+00 -1.11142228e+00
 -1.09799750e+00 -4.48546605e-01 -1.15370633e+00  1.66121555e+00
 -2.63968783e-01  1.28011294e+00 -5.69422206e-01  2.85183999e-02
 -7.51109577e-01 -7.56584066e-01 -5.61975011e-01  1.87460582e-01
 -8.42579093e-01 -1.29926961e+00 -2.74224535e-01  4.99357334e-02
  5.45396904e-01  2.24962763e+00  1.65207199e-01 -1.35484730e+00
  7.73836253e-01  2.01925206e+00 -9.63911699e-01 -6.71297565e-01
 -1.98187315e-01 -1.03840782e+00 -7.42101552e-02 -5.81944571e-01
  9.68610339e-03 -1.19369389e+00  1.30003797e+00 -1.42683577e+00
  1.87143805e+00  2.07215276e+00  5.11587952e-01 -7.82151824e-01
 -3.76468673e-05 -4.59328573e-01 -7.44696424e-01  1.42022236e+00
 -2.50161303e+00  1.39746739e+00  1.79833332e+00 -3.21149503e-01
 -2.06924797e+00 -5.82047247e-01 -8.78037976e-02  1.65609627e+00
 -2.83200760e-01  4.58274

math functions (methods) associated with a numpy arry

In [27]:
m1=A_randn.mean()
print(m1)

0.019742769294117935


In [28]:
s1=A_randn.std()
print(s1)

1.0218418316904438


get a list of such methods using the function dir

In [29]:
dir(A_randn)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

more information about the methods can be found at <br> https://docs.scipy.org/doc/numpy/reference/routines.html

Go back to slide "Numerical Data Types in Numpy"