Numpy Array seems to be very similar to List <br>
List  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~ 1D array <br> 
list of list &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              ~ 2D array <br> 
list of list of list &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~ 3D array  <br> 
...  <br> 
list of list of list of... ~ N D array <br> 
Why do we need Numpy Array ?

In [1]:
import numpy as np

operators +, * for a list

In [2]:
A = [1, 2, 3]
B = [4, 5, 6]
C = A + B
print(C)

[1, 2, 3, 4, 5, 6]


In [3]:
A = [1, 2, 3]
B = A*3
print(B)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


'+ - * /' are math operators for numpy array

In [4]:
A = np.array([1, 2, 3], dtype='int32')
B = np.array([4, 5, 6], dtype='int32')
C = A + B
print(C)

[5 7 9]


In [5]:
A = np.array([1, 2, 3], dtype='int32')
B = A*3
print(B)

[3 6 9]


A * B => A[n]*B[n] for each n

In [6]:
A = np.array([1, 2, 3], dtype='int32')
B = np.array([4, 5, 6], dtype='int32')
C = A * B
print(C)

[ 4 10 18]


operations on Numpy Array can be much faster than operations (a for loop) on List 

In [7]:
A = list(range(0, 10000000))
A[0:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
import timeit
t1=timeit.default_timer()
for k in range(0, 10000000):
    A[k] *= 3 # A[k]*=3 is the same as A[k]=A[k]*3
#end
t2=timeit.default_timer()
time_list_for=t2-t1
print('time cost:', time_list_for, '(seconds)')

time cost: 1.4224642629999948 (seconds)


vectorized operation on a numpy array

In [9]:
B = np.array(A)
t1=timeit.default_timer()

B *= 3 # array-oriented operation (a.k.a vectorized operation)

t2=timeit.default_timer()
time_array=t2-t1
print('time cost:', time_array, '(seconds)')

time cost: 0.01740745600000082 (seconds)


time_list_for is the time cost of the for loop over a list <br>
time_array is the time cost of the vectorized operation <br>

In [10]:
time_list_for/time_array

81.71580402098547

but, try not to use a for loop to go over a numpy array in time sensitive applications ...

In [11]:
B = np.array(A)
t1=timeit.default_timer()
for k in range(0, len(B)):
    B[k] *= 3    
#end
t2=timeit.default_timer()
time_array_for=t2-t1
print('time cost:', time_array_for, '(seconds)')

time cost: 3.5722699830000124 (seconds)


# Other differences

append a number to a list v.s. apend a number to a numpy array

In [12]:
aList=[0, 1, 2, 3]
print('id(aList)=', id(aList))

id(aList)= 4586431432


In [13]:
aList.append(4)
print('id(aList)=', id(aList))
aList

id(aList)= 4586431432


[0, 1, 2, 3, 4]

In [14]:
A = np.array([0, 1, 2, 3], dtype='int32')
A

array([0, 1, 2, 3], dtype=int32)

In [15]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [16]:
B = np.append(A, 4)
B

array([0, 1, 2, 3, 4])

In [17]:
id(A)

5233030528

In [18]:
id(B)

5233079600

In [19]:
A

array([0, 1, 2, 3], dtype=int32)

concatenate two lists using + <br>
concatenate two numpy arrays using np.concatenate <br>

In [20]:
A + A

array([0, 2, 4, 6], dtype=int32)

In [21]:
C = np.concatenate([A, A])
C

array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int32)

repeat a list N times using list * N <br>
repeat a numpy array N times using np.tile(array, N)

In [22]:
A*3

array([0, 3, 6, 9], dtype=int32)

In [23]:
D = np.tile(A, 3)
D

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int32)